<!DOCTYPE html>
<html>
  <body>
    <script>
      const fakeAsyncFunc = (input, err) => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            if (err) {
              reject(err);
              return
            }
            resolve(input)
          })
        }) 
      }

      const hoge = async () => {
        try {
          const ret = await fakeAsyncFunc('hoge', 'gyan')
          console.log(ret)
        } catch (err) {
          // console.error('hoge error')
          throw new Error(err);
        }
      }

      const fuga = async () => {
        try {
          await hoge();
          const ret = await fakeAsyncFunc('fuga')
          console.log(ret)
        } catch (err) {
          console.error('fuga error')
        }
      }

      fuga()
        .then((ret) => {
          
        })
        .catch((err) => {
          console.error(err)
        })

    </script>
  </body>
</html>